version: "3.9" 
services:
  slic3r:
    build:
      context: .
    command: octocat.stl
    image: slicer:latest
    environment:
      - SLICE_CFG=config.ini
    volumes:
      - ./resources:/github/workspace
volumes:
  resources: {}