on: 
  project_card:
    types: [moved]
  workflow_dispatch:
    inputs:
      stlURL:
        description: 'URL of STL to slice'     
        required: false

name: 3d print workflow
jobs:
  get-stl-file:
    runs-on: ubuntu-latest
    steps:     
    - uses: actions/checkout@v2
    - name: slice stl and upload gcode
      uses: ./
      env:
        SLICE_CFG: resources/config.ini
        GITHUB_PROJECT_CONTEXT: ${{ toJson(github) }}
        PROJECT_CARD_ID: ${{ github.event.project_card.id }}
        NOTE_TEXT: ${{ github.event.project_card.note }}
        INPUT_STL_URL: ${{ github.event.inputs.stlURL }}


